# Generated by Django 2.0 on 2020-09-30 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.BinaryField()),
                ('currency', models.CharField(max_length=15)),
                ('time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='twits')),
                ('File', models.FileField(blank=True, null=True, upload_to='files')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twits.twit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
