# Generated by Django 2.0 on 2021-03-17 21:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now=True)),
                ('File', models.FileField(blank=True, null=True, upload_to='files')),
                ('likes', models.ManyToManyField(related_name='commect_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'کامنت توییت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 3, 17, 21, 11, 47, 424357, tzinfo=utc))),
                ('Type', models.CharField(choices=[('تبلیغ', 'تبلیغ'), ('تکرار', 'تکرار'), ('توهین', 'توهین')], max_length=5)),
                ('status', models.CharField(choices=[('رد', 'رد'), ('پذیرفته', 'پذیرفته'), ('ندیده', 'ندیده')], default='ندیده', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now=True)),
                ('retwit', models.BooleanField(default=False)),
                ('File', models.FileField(blank=True, null=True, upload_to='files')),
                ('has_image', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('shamsi_date', models.CharField(default='1399/11/26', max_length=11)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.currency')),
                ('likes', models.ManyToManyField(related_name='twit_likes', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twits.twit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'توییت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='twit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twits.twit'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='twits.twit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
