# Generated by Django 2.0 on 2020-09-30 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twits', '0002_auto_20201001_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.BinaryField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('File', models.FileField(blank=True, null=True, upload_to='files')),
                ('likes', models.ManyToManyField(related_name='commect_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='twit',
            name='image',
        ),
        migrations.AddField(
            model_name='twit',
            name='likes',
            field=models.ManyToManyField(related_name='twit_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='twits.twit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
