# Generated by Django 2.0 on 2020-09-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0003_auto_20201001_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='retwit',
            field=models.BooleanField(default=False),
        ),
    ]
