# Generated by Django 2.0 on 2020-10-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0004_twit_retwit'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='has_image',
            field=models.BooleanField(default='False'),
        ),
    ]
