# Generated by Django 2.0 on 2020-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0005_twit_has_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
