# Generated by Django 2.0 on 2020-12-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0007_auto_20201217_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twits.twit'),
        ),
    ]
