# Generated by Django 2.0 on 2020-09-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200928_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
