# Generated by Django 2.0 on 2020-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201001_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.BinaryField(default=b'A'),
        ),
    ]
