# Generated by Django 2.0 on 2020-12-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201002_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
