# Generated by Django 2.0 on 2021-03-17 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('RefID', models.CharField(blank=True, max_length=30, null=True)),
                ('Authority', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(choices=[('payment', 'payment'), ('pending', 'pending'), ('done', 'done')], default='payment', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='تعداد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cart', verbose_name='سبد خرید')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('off', models.IntegerField(default=0, verbose_name='تخفیف به درصد')),
                ('details', models.TextField(default='', verbose_name='توضیحات')),
                ('details2', models.TextField(default='', verbose_name='توضیحات پایین')),
                ('status', models.CharField(choices=[('موچود', 'موچود'), ('ناموچود', 'ناموچود')], default=('موچود', 'موچود'), max_length=10)),
                ('tags', models.CharField(default='crypto;BTC;miner', max_length=50, verbose_name='تگ\u200cها(با ; جدا شوند)')),
                ('image1', models.FileField(upload_to='products', verbose_name='تصویر اول')),
                ('image2', models.FileField(blank=True, null=True, upload_to='products', verbose_name='تصویر دوم')),
                ('image3', models.FileField(blank=True, null=True, upload_to='products', verbose_name='تصویر سوم')),
                ('image4', models.FileField(blank=True, null=True, upload_to='products', verbose_name='تصویر اول')),
                ('image5', models.FileField(blank=True, null=True, upload_to='products', verbose_name='تصویر دوم')),
                ('image6', models.FileField(blank=True, null=True, upload_to='products', verbose_name='تصویر سوم')),
            ],
            options={
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='product_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shamsi_date', models.CharField(max_length=11)),
                ('text', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_in', to='products.product_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_group'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
    ]
