# Generated by Django 2.0 on 2020-12-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_comment_shamsi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_comment',
            name='shamsi_date',
            field=models.CharField(max_length=11),
        ),
    ]
