# Generated by Django 2.0 on 2020-12-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201218_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.FileField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.FileField(null=True, upload_to='products'),
        ),
    ]
